{{- $fullName := include "yourbiz-be.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "yourbiz-be.labels" . | nindent 4 }}
data:
  redisson.yaml: |-
    singleServerConfig:
      address: {{ .Values.redis.address }}
      password: {{ .Values.redis.password }}
      idleConnectionTimeout: 10000
      pingTimeout: 1000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      reconnectionTimeout: 3000
      failedAttempts: 3
      subscriptionsPerConnection: 5
      clientName: null
      subscriptionConnectionMinimumIdleSize: 1
      subscriptionConnectionPoolSize: 50
      connectionMinimumIdleSize: 10
      connectionPoolSize: 64
      database: 0
    threads: 0
    nettyThreads: 0
    codec: !<org.redisson.codec.JsonJacksonCodec> {}

  application.yaml: |-
    server:
      port: {{ .Values.serverPort }}
    
    ## Spring properties
    spring:
      servlet:
        multipart:
          max-file-size: {{ .Values.localFileStore.maxFileSize }}
          max-request-size: {{ .Values.localFileStore.maxFileSize }}

      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        {{- if .Values.mysql.enabled }}
        url: jdbc:mysql://{{ $fullName }}-mysql:{{ .Values.mysql.service.port | default 3306 }}/{{ .Values.mysql.dbname }}{{- if .Values.mysql.extralJdbcArgs }}{{- printf "?%s" .Values.mysql.extralJdbcArgs -}}{{- end }}
        username: {{ .Values.mysql.username }}
        {{- else }}
        url: {{ .Values.externalMySql.url }}
        username: {{ .Values.externalMySql.username }}
        {{- end }}
        password: ${MYSQL_PASSWORD}

      redis:
        redisson:
          config: classpath:/redisson.yaml

      devtools:
        add-properties: true

      {{- if .Values.rabbitmq.enabled }}
      rabbitmq:
        host: {{ .Values.rabbitmq.host }}
        port: {{ .Values.rabbitmq.port | default 5672 }}
        username: {{ .Values.rabbitmq.username }}
        virtual-host: {{ .Values.rabbitmq.virtualHost }}
        password: ${RABBITMQ_PASSWORD}
      {{- end }}

    ## Application properties
    application:
      file-store:
        path: {{ .Values.localFileStore.savePath }}
        base-url: {{ .Values.localFileStore.endpoint }}

      security:
        jwt:
          secret: ${JWT_SECRET}

      cors:
        allowCredentials: true
        allowedOrigins: ['*']
        allowedMethods: ['*']
        allowedHeaders: ['*']

      oss:
        access-key-id: ${OSS_ACCESS_KEY_ID}
        access-key-secret: ${OSS_ACCESS_KEY_SECRET}
        endpoint: {{ .Values.oss.endpoint }}
        bucket-name: {{ .Values.oss.bucketName }}
        expiration: {{ .Values.oss.expiration }}
        max-size: {{ .Values.oss.maxSize }}
        callback-url: {{ .Values.oss.callbackUrl }}

      wechat:
        app-id: {{ .Values.wechat.appId }}
        token: ${WECHAT_TOKEN}
        app-secret: ${WECHAT_APP_SECRET}

      ding-talk:
        access-token: ${DING_TALK_ACCESS_TOKEN}
{{ .Values.applicationConfigMap.extra | nindent 6 }}

